name: Deploy Migrations to PRD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link and Deploy Migrations
        run: |
          supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID_PRD }} --password ${{ secrets.SUPABASE_DB_PASSWORD_PRD }}
          supabase db push --password ${{ secrets.SUPABASE_DB_PASSWORD_PRD }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
